apiVersion: apps/v1
kind: Deployment
metadata:
  name: jstodobackend
  labels:
    app: jstodobackend
spec:
  replicas: 1
  selector:
    matchLabels:
     app: jstodobackend
  template:
    metadata:
      labels:
        app: jstodobackend
    spec:
      containers:
      - name: jstodobackend
        image: kamilhomer/jstodobackend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80