apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: aaa.mzylowski.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 5000