apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homernik-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - bbb.mzylowski.pl
    secretName: bbb.mzylowski.pl
  rules:
  - host: bbb.mzylowski.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: website
          servicePort: 80